### ISSUE TITLE
Is project still maintained

### ISSUE THREAD

**Issue by psukys** [nukeop/smash#1]
Hey, I find this project nice and would like to contribute some functionality (i.e. search, minor UI fixes (logging in still shows login button), etc). Is this project still maintained, so that I can contribute back to it, or should I stay with my fork?

**Comment by nukeop** [comment]
I haven't worked on it in a while, but if you want to contribute to it, you're more than welcome. I'll make sure to review your changes properly and integrate them.

I don't really have a user account system for it, so the login is kinda "fake", as in, you can set a secret environment variable that serves as a password for accessing the moderation panel. Since this was only created so that me and a couple of friends could share funny quotes between us, we've never really needed user accounts.

**Comment by psukys** [comment]
Great, then I'll just add issues and propose through merge requests
